version: '3.8'

services:
  db:
    image: postgres:13 
    container_name: backend_db
    environment:
      POSTGRES_DB: ${DB_NAME:-backend_db}
      POSTGRES_USER: ${DB_USER:-admin}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-admin}
    ports:
      - "5432:5432"
    volumes:
      - ${DB_DATA_PATH:-./data/backend_db}:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    container_name: backend
    command: /docker-entrypoint.sh
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

  room-reader:
    build:
      context: ./room_reader
    container_name: room_reader
    command: python main.py
    ports:
      - "5000:5000"
    depends_on:
      - backend
    env_file:
      - .env

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend