# Generated by Django 5.1.3 on 2024-11-13 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('card', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomReader',
            fields=[
                ('uid', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('ip', models.GenericIPAddressField()),
                ('reader_state', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomEntryLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('log_type', models.CharField(choices=[('entry', 'Entry'), ('exit', 'Exit'), ('denied', 'Denied')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='card.card')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='room_reader.roomreader')),
            ],
        ),
        migrations.CreateModel(
            name='UserAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access', models.BooleanField(default=False)),
                ('room_reader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='room_reader.roomreader')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'room_reader')},
            },
        ),
    ]
