# Generated by Django 5.1.3 on 2024-11-14 12:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_reader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomreader',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
