# Generated by Django 5.1.3 on 2024-12-03 09:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('card', '0001_initial'),
        ('room_reader', '0002_alter_roomreader_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='useragreement',
            name='card_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='card.card'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='useragreement',
            unique_together={('card_id', 'room_reader')},
        ),
        migrations.RemoveField(
            model_name='useragreement',
            name='user',
        ),
    ]
