# Generated by Django 5.1.3 on 2024-12-08 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room_reader', '0003_alter_useragreement_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roomreader',
            old_name='reader_state',
            new_name='active',
        ),
    ]
