# Generated by Django 5.1.3 on 2024-12-03 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room_reader', '0003_alter_useragreement_unique_together_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useragreement',
            old_name='card_id',
            new_name='card',
        ),
    ]
