# Generated by Django 5.1.3 on 2024-12-09 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room_reader', '0004_rename_reader_state_roomreader_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useragreement',
            name='access',
        ),
    ]
