# Generated by Django 5.1.3 on 2024-12-09 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('room_reader', '0005_remove_useragreement_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='useragreement',
            name='status',
            field=models.CharField(choices=[('allowed', 'Allowed'), ('not_allowed', 'Not Allowed'), ('pending', 'Pending')], default='pending', max_length=15),
            preserve_default=False,
        ),
    ]
